import { CategoryExpense, MonthCategoryData } from './CategoryExpenseTrend';

export const expenseCategories: CategoryExpense[] = [
  { name: 'Mileage', color: '#9575CD' },
  { name: 'Dues Subscriptions', color: '#F2FCE2' },
  { name: 'Auditing Serv Fees', color: '#8B5CF6' },
  { name: 'Hotel/Lodging', color: '#D3E4FD' },
  { name: 'Meals', color: '#E5DEFF' },
  { name: 'Others', color: '#F1F0FB' },
  { name: 'Professional Fees', color: '#FFDEE2' },
  { name: 'Gasoline', color: '#F97316' },
  { name: 'Office Supplies', color: '#FEF7CD' },
  { name: 'Business Meals', color: '#EC4899' },
  { name: 'Postage & Freight', color: '#FEC6A1' },
  { name: 'Registration Fees', color: '#8B5CF6' },
  { name: 'Parking/Tolls', color: '#0EA5E9' },
  { name: 'Air/Taxi/Uber', color: '#FDE1D3' },
  { name: 'Baggage Fees', color: '#FEC6A1' },
  { name: 'Rental Car', color: '#F59E0B' },
];

export const monthlyExpenseTrendData: MonthCategoryData[] = [
  {
    month: 'Apr 2024',
    'Mileage': 1800,
    'Dues Subscriptions': 900,
    'Auditing Serv Fees': 1200,
    'Hotel/Lodging': 1200,
    'Meals': 1300,
    'Others': 800,
    'Professional Fees': 600,
    'Gasoline': 700,
    'Office Supplies': 400,
    'Business Meals': 460,
    'Postage & Freight': 300,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 9160,
  },
  {
    month: 'May 2024',
    'Mileage': 3400,
    'Dues Subscriptions': 3200,
    'Auditing Serv Fees': 5800,
    'Hotel/Lodging': 7200,
    'Meals': 6800,
    'Others': 12500,
    'Professional Fees': 1500,
    'Gasoline': 1100,
    'Office Supplies': 1200,
    'Business Meals': 840,
    'Postage & Freight': 900,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 44440,
  },
  {
    month: 'Jun 2024',
    'Mileage': 2100,
    'Dues Subscriptions': 1200,
    'Auditing Serv Fees': 1400,
    'Hotel/Lodging': 1800,
    'Meals': 1400,
    'Others': 6800,
    'Professional Fees': 0,
    'Gasoline': 0,
    'Office Supplies': 0,
    'Business Meals': 170,
    'Postage & Freight': 0,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 14870,
  },
  {
    month: 'Jul 2024',
    'Mileage': 2800,
    'Dues Subscriptions': 1500,
    'Auditing Serv Fees': 2100,
    'Hotel/Lodging': 3800,
    'Meals': 4200,
    'Others': 8000,
    'Professional Fees': 1200,
    'Gasoline': 1100,
    'Office Supplies': 800,
    'Business Meals': 750,
    'Postage & Freight': 300,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 26550,
  },
  {
    month: 'Aug 2024',
    'Mileage': 3100,
    'Dues Subscriptions': 2200,
    'Auditing Serv Fees': 3200,
    'Hotel/Lodging': 4500,
    'Meals': 4900,
    'Others': 8500,
    'Professional Fees': 2800,
    'Gasoline': 1900,
    'Office Supplies': 1200,
    'Business Meals': 950,
    'Postage & Freight': 750,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 34000,
  },
  {
    month: 'Sep 2024',
    'Mileage': 1500,
    'Dues Subscriptions': 1300,
    'Auditing Serv Fees': 1900,
    'Hotel/Lodging': 2500,
    'Meals': 2800,
    'Others': 5400,
    'Professional Fees': 800,
    'Gasoline': 700,
    'Office Supplies': 400,
    'Business Meals': 250,
    'Postage & Freight': 150,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 17700,
  },
  {
    month: 'Oct 2024',
    'Mileage': 2600,
    'Dues Subscriptions': 1900,
    'Auditing Serv Fees': 2900,
    'Hotel/Lodging': 3700,
    'Meals': 3900,
    'Others': 9000,
    'Professional Fees': 1500,
    'Gasoline': 1100,
    'Office Supplies': 0,
    'Business Meals': 670,
    'Postage & Freight': 0,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 26270,
  },
  {
    month: 'Nov 2024',
    'Mileage': 3700,
    'Dues Subscriptions': 2200,
    'Auditing Serv Fees': 3800,
    'Hotel/Lodging': 5800,
    'Meals': 6200,
    'Others': 10200,
    'Professional Fees': 2400,
    'Gasoline': 1700,
    'Office Supplies': 0,
    'Business Meals': 830,
    'Postage & Freight': 0,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 36830,
  },
  {
    month: 'Dec 2024',
    'Mileage': 1800,
    'Dues Subscriptions': 900,
    'Auditing Serv Fees': 1700,
    'Hotel/Lodging': 2400,
    'Meals': 2700,
    'Others': 5800,
    'Professional Fees': 0,
    'Gasoline': 0,
    'Office Supplies': 0,
    'Business Meals': 360,
    'Postage & Freight': 300,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 15960,
  },
  {
    month: 'Jan 2025',
    'Mileage': 2500,
    'Dues Subscriptions': 1500,
    'Auditing Serv Fees': 2600,
    'Hotel/Lodging': 3600,
    'Meals': 4100,
    'Others': 6700,
    'Professional Fees': 0,
    'Gasoline': 0,
    'Office Supplies': 800,
    'Business Meals': 410,
    'Postage & Freight': 500,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 22710,
  },
  {
    month: 'Feb 2025',
    'Mileage': 3100,
    'Dues Subscriptions': 1900,
    'Auditing Serv Fees': 3200,
    'Hotel/Lodging': 4200,
    'Meals': 4800,
    'Others': 7200,
    'Professional Fees': 0,
    'Gasoline': 0,
    'Office Supplies': 1100,
    'Business Meals': 750,
    'Postage & Freight': 1000,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 27250,
  },
  {
    month: 'Mar 2025',
    'Mileage': 2200,
    'Dues Subscriptions': 1000,
    'Auditing Serv Fees': 2400,
    'Hotel/Lodging': 3200,
    'Meals': 3800,
    'Others': 4500,
    'Professional Fees': 0,
    'Gasoline': 0,
    'Office Supplies': 800,
    'Business Meals': 450,
    'Postage & Freight': 500,
    'Registration Fees': 0,
    'Parking/Tolls': 0,
    'Air/Taxi/Uber': 0,
    'Baggage Fees': 0,
    'Rental Car': 0,
    totalAmount: 18850,
  },
];

export const categoryInsights = {
  highestCategory: 'Expense - Other',
  highestAmount: 102462.5,
  lowestCategory: 'Travel (Personal Vehicle)',
  lowestAmount: 0,
};
