
import { CategoryExpense, MonthCategoryData } from './CategoryExpenseTrend';

export const expenseCategories: CategoryExpense[] = [
  { name: 'Travel - International', color: '#9575CD' },
  { name: 'Travel - Intercity-Personal Vehicle', color: '#4CAF50' },
  { name: 'Travel - Intercity-Cab/Bus/Flight', color: '#66BB6A' },
  { name: 'Travel - Intracity-Cab/Bus/Auto', color: '#81C784' },
  { name: 'Travel - Intracity-Personal Vehicle', color: '#A5D6A7' },
  { name: 'Per-Diem - International', color: '#37474F' },
  { name: 'Per-Diem - Domestic', color: '#78909C' },
  { name: 'Expense - Other', color: '#EF5350' },
  { name: 'Expense - Mobile', color: '#FF8A65' },
  { name: 'Expense - Internet', color: '#FFAB91' },
  { name: 'Expense-Medical', color: '#F06292' },
  { name: 'Relocation Reimbursement', color: '#7986CB' },
  { name: 'Standard Category', color: '#26A69A' },
  { name: 'IT & Software', color: '#9C27B0' },
  { name: 'Health and Wellness', color: '#EC407A' },
  { name: 'Cash', color: '#26C6DA' },
  { name: 'Office Supplies & Equipment', color: '#66BB6A' },
  { name: 'Professional Development', color: '#7986CB' },
  { name: 'Remote Work Setup', color: '#29B6F6' },
  { name: 'Travel & Transportation', color: '#FFB74D' },
  { name: 'Meals & Entertainment', color: '#FF7043' },
  { name: 'Lodging & Accommodation', color: '#FFA726' },
  { name: 'Miscellaneous Business Expenses', color: '#8D6E63' },
  { name: 'Travel (Personal Vehicle)', color: '#FDD835' },
];

export const monthlyExpenseTrendData: MonthCategoryData[] = [
  {
    month: 'Apr 2024',
    'Relocation Reimbursement': 1200,
    'Standard Category': 1800,
    'Expense - Other': 2500,
    'Travel - Intracity-Personal Vehicle': 1400,
    'Travel - International': 800,
    'Per-Diem - Domestic': 600,
    'Health and Wellness': 860,
    totalAmount: 9160,
  },
  {
    month: 'May 2024',
    'Relocation Reimbursement': 3200,
    'Standard Category': 10500,
    'Expense - Other': 12500,
    'Travel - Intracity-Personal Vehicle': 5100,
    'Travel - International': 6200,
    'Per-Diem - Domestic': 3500,
    'Health and Wellness': 3440,
    totalAmount: 44440,
  },
  {
    month: 'Jun 2024',
    'Relocation Reimbursement': 1800,
    'Standard Category': 1500,
    'Expense - Other': 6800,
    'Travel - Intracity-Personal Vehicle': 1200,
    'Travel - International': 1500,
    'Per-Diem - Domestic': 1100,
    'Health and Wellness': 970,
    totalAmount: 14870,
  },
  {
    month: 'Jul 2024',
    'Relocation Reimbursement': 2800,
    'Standard Category': 3100,
    'Expense - Other': 8000,
    'Travel - Intracity-Personal Vehicle': 6800,
    'Travel - International': 2100,
    'Per-Diem - Domestic': 2800,
    'Health and Wellness': 950,
    totalAmount: 26550,
  },
  {
    month: 'Aug 2024',
    'Relocation Reimbursement': 3100,
    'Standard Category': 7000,
    'Expense - Other': 8500,
    'Travel - Intracity-Personal Vehicle': 7900,
    'Travel - International': 3200,
    'Per-Diem - Domestic': 2200,
    'Health and Wellness': 2100,
    totalAmount: 34000,
  },
  {
    month: 'Sep 2024',
    'Relocation Reimbursement': 2100,
    'Standard Category': 1800,
    'Expense - Other': 5400,
    'Travel - Intracity-Personal Vehicle': 3200,
    'Travel - International': 2900,
    'Per-Diem - Domestic': 1300,
    'Health and Wellness': 1000,
    totalAmount: 17700,
  },
  {
    month: 'Oct 2024',
    'Relocation Reimbursement': 2600,
    'Standard Category': 4100,
    'Expense - Other': 9000,
    'Travel - Intracity-Personal Vehicle': 4500,
    'Travel - International': 3500,
    'Per-Diem - Domestic': 1900,
    'Health and Wellness': 870,
    totalAmount: 26470,
  },
  {
    month: 'Nov 2024',
    'Relocation Reimbursement': 4000,
    'Standard Category': 6500,
    'Expense - Other': 10200,
    'Travel - Intracity-Personal Vehicle': 7100,
    'Travel - International': 5800,
    'Per-Diem - Domestic': 2200,
    'Health and Wellness': 1030,
    totalAmount: 36830,
  },
  {
    month: 'Dec 2024',
    'Relocation Reimbursement': 1900,
    'Standard Category': 1800,
    'Expense - Other': 5800,
    'Travel - Intracity-Personal Vehicle': 2800,
    'Travel - International': 2000,
    'Per-Diem - Domestic': 900,
    'Health and Wellness': 760,
    totalAmount: 15960,
  },
  {
    month: 'Jan 2025',
    'Relocation Reimbursement': 2500,
    'Standard Category': 3400,
    'Expense - Other': 6700,
    'Travel - Intracity-Personal Vehicle': 4900,
    'Travel - International': 3000,
    'Per-Diem - Domestic': 1500,
    'Health and Wellness': 710,
    totalAmount: 22710,
  },
  {
    month: 'Feb 2025',
    'Relocation Reimbursement': 3100,
    'Standard Category': 4200,
    'Expense - Other': 7200,
    'Travel - Intracity-Personal Vehicle': 6300,
    'Travel - International': 3800,
    'Per-Diem - Domestic': 1900,
    'Health and Wellness': 750,
    totalAmount: 27250,
  },
  {
    month: 'Mar 2025',
    'Relocation Reimbursement': 2200,
    'Standard Category': 6000,
    'Expense - Other': 4500,
    'Travel - Intracity-Personal Vehicle': 2800,
    'Travel - International': 1800,
    'Per-Diem - Domestic': 1000,
    'Health and Wellness': 550,
    totalAmount: 18850,
  },
];

export const categoryInsights = {
  highestCategory: 'Expense - Other',
  highestAmount: 102462.5,
  lowestCategory: 'Travel (Personal Vehicle)',
  lowestAmount: 0,
};
